#!/usr/bin/env python3
"""
src/generate_research_report.py
Consolidates the markdown report from report_generator.py and attaches interpretation.
"""
from __future__ import annotations

from pathlib import Path
import sys

BASE_DIR   = Path(__file__).resolve().parent.parent
SCRIPTS_DIR = BASE_DIR / "scripts"
sys.path.insert(0, str(SCRIPTS_DIR))

from report_generator import run as generate_report


def attach_foreword(report_text: str) -> str:
    """Prepend a GARCH-QUANT branded foreword to the report."""
    foreword = (
        "# GARCH-QUANT Research Brief\n"
        "| Korea Semiconductor Trade Signal | Automated Report |\n\n"
        "*Generated by GARCH-QUANT Korea Trade Signal Pipeline · "
        "Do not trade on this report alone · Verify all HS code mappings before citing*\n\n---\n\n"
    )
    return foreword + report_text


def main():
    out_path = generate_report()
    text = out_path.read_text(encoding="utf-8")
    enhanced = attach_foreword(text)
    out_path.write_text(enhanced, encoding="utf-8")
    print(f"[generate_research_report] written: {out_path}")
    return out_path


if __name__ == "__main__":
    main()
